### PR TITLE
feat: remove name and ns from Node struct and add support for param loading

### PR DESCRIPTION
**Pull request by jazi007**
Implementation for:

- https://github.com/tier4/safe_drive/issues/17
- https://github.com/tier4/safe_drive/issues/19 

Also fixing some clippy issue and formatting code

### CODE REVIEW

**Comment by jazi007** [comment]
@ytakano ready for review :-)

**Comment by ytakano** [comment]
Thank you. I will test it tomorrow, and push it to crates.io.

**Comment by jazi007** [comment]
@ytakano any news about tests and publish ? 😀

**Comment by ytakano** [comment]
> @ytakano any news about tests and publish ? 😀

Oh. I will!

**Comment by jazi007** [comment]
Perfect 🤩

**Pull request merged**
