### PR TITLE
fix: hot fix for win and linux for humble

### PR DESCRIPTION
**Pull request by jazi007**
Something went wrong when generation was updated.
When ros node are built on one machine and then used in another one, failed due to InvalidArgument error when a subscriber is created

1. I fixed: https://github.com/tier4/ros2msg_to_rs/pull/1 so now the size is well checked
2. regenerated the bindgen and msg for humble

Now compilation is ok without warning under linux and windows and nodes can be built on one machine and used in another one

### CODE REVIEW

**Comment by jazi007** [comment]
@ytakano could you please give it a try and publish a new version to crates.io ;-)

**Comment by jazi007** [comment]
another long runner one for colcon too: https://github.com/tier4/colcon-cargo/pull/1

**Comment by jazi007** [comment]
@ytakano I tested the main branch and still have warning for windows.
This PR contains also the regeneration for rcl which fixes those issues not only the size check

Here's the kind of warnings observed, which is fixed by this PR

```bash
warning: `action_msgs__srv__CancelGoal_Response__Sequence__fini` redeclared with a different signature
     --> src\rcl\humble.rs:14269:5
      |
14269 | /     pub fn action_msgs__srv__CancelGoal_Response__Sequence__fini(
14270 | |         array: *mut action_msgs__srv__CancelGoal_Response__Sequence,
14271 | |     );
      | |_____^ this signature doesn't match the previous declaration
      |
     ::: src\msg\humble\interfaces\action_msgs\srv\cancel_goal.rs:26:5
      |
26    |       fn action_msgs__srv__CancelGoal_Response__Sequence__fini(msg: *mut CancelGoalResponseSeqRaw);
      |       -------------------------------------------------------------------------------------------- `action_msgs__srv__CancelGoal_Response__Sequence__fini` previously declared here
      |
      = note: expected `unsafe extern "C" fn(*mut CancelGoalResponseSeqRaw)`
                 found `unsafe extern "C" fn(*mut action_msgs__srv__CancelGoal_Response__Sequence)`

warning: `safe_drive` (lib) generated 18 warnings
```

**Comment by ytakano** [comment]
> @ytakano I tested the main branch and still have warning for windows. This PR contains also the regeneration for rcl which fixes those issues not only the size check
> 
> Here's the kind of warnings observed, which is fixed by this PR
> 
> ```shell
> warning: `action_msgs__srv__CancelGoal_Response__Sequence__fini` redeclared with a different signature
>      --> src\rcl\humble.rs:14269:5
>       |
> 14269 | /     pub fn action_msgs__srv__CancelGoal_Response__Sequence__fini(
> 14270 | |         array: *mut action_msgs__srv__CancelGoal_Response__Sequence,
> 14271 | |     );
>       | |_____^ this signature doesn't match the previous declaration
>       |
>      ::: src\msg\humble\interfaces\action_msgs\srv\cancel_goal.rs:26:5
>       |
> 26    |       fn action_msgs__srv__CancelGoal_Response__Sequence__fini(msg: *mut CancelGoalResponseSeqRaw);
>       |       -------------------------------------------------------------------------------------------- `action_msgs__srv__CancelGoal_Response__Sequence__fini` previously declared here
>       |
>       = note: expected `unsafe extern "C" fn(*mut CancelGoalResponseSeqRaw)`
>                  found `unsafe extern "C" fn(*mut action_msgs__srv__CancelGoal_Response__Sequence)`
> 
> warning: `safe_drive` (lib) generated 18 warnings
> ```

I see.
It seems that some C functions are regenerated by bindgen.

I have fixed now.
Does it work?

**Comment by jazi007** [comment]
looks like we are getting into UB now :-)

```bash
error: casting references to a bigger memory layout than the backing allocation is undefined behavior, even if the reference is unused
  --> src\action.rs:59:31
   |
58 |     let status_seq_ptr = &mut statuses.msg.status_list as *mut _ as *mut GoalStatusSeq<0>;
   |                          ----------------------------------------------------------------
   |                          |    |
   |                          |    backing allocation comes from here
   |                          casting happend here
59 |     let status_seq = unsafe { &mut (*status_seq_ptr) };
   |                               ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: casting from `bindgen_action_msgs__msg__GoalStatus__Sequence` (16 bytes) to `action_msgs::msg::goal_status::GoalStatusSeq<0>` (24 bytes)
   = note: `#[deny(invalid_reference_casting)]` on by default

error: casting references to a bigger memory layout than the backing allocation is undefined behavior, even if the reference is unused
   --> src\selector.rs:691:55
    |
689 |   ...                   let goal_seq_ptr = &process_response.msg.goals_canceling as *const _
    |                                            ------------------------------------- backing allocation comes from here
    |  __________________________________________|
    | |
690 | | ...                       as *const GoalInfoSeq<0>;
    | |__________________________________________________- casting happend here
691 |   ...                   let candidates = unsafe { &(*goal_seq_ptr) };
    |                                                   ^^^^^^^^^^^^^^^^
    |
    = note: casting from `rcl::humble::bindgen_action_msgs__msg__GoalInfo__Sequence` (16 bytes) to `goal_info::GoalInfoSeq<0>` (24 bytes)

error: could not compile `safe_drive` (lib) due to 2 previous errors
```

**Comment by ytakano** [comment]
Ah.
It seems that `size_t` of Windows is 32 bits, but `size_t` of Linux is 64 bits.

> looks like we are getting into UB now :-)
> 
> ```shell
> error: casting references to a bigger memory layout than the backing allocation is undefined behavior, even if the reference is unused
>   --> src\action.rs:59:31
>    |
> 58 |     let status_seq_ptr = &mut statuses.msg.status_list as *mut _ as *mut GoalStatusSeq<0>;
>    |                          ----------------------------------------------------------------
>    |                          |    |
>    |                          |    backing allocation comes from here
>    |                          casting happend here
> 59 |     let status_seq = unsafe { &mut (*status_seq_ptr) };
>    |                               ^^^^^^^^^^^^^^^^^^^^^^
>    |
>    = note: casting from `bindgen_action_msgs__msg__GoalStatus__Sequence` (16 bytes) to `action_msgs::msg::goal_status::GoalStatusSeq<0>` (24 bytes)
>    = note: `#[deny(invalid_reference_casting)]` on by default
> 
> error: casting references to a bigger memory layout than the backing allocation is undefined behavior, even if the reference is unused
>    --> src\selector.rs:691:55
>     |
> 689 |   ...                   let goal_seq_ptr = &process_response.msg.goals_canceling as *const _
>     |                                            ------------------------------------- backing allocation comes from here
>     |  __________________________________________|
>     | |
> 690 | | ...                       as *const GoalInfoSeq<0>;
>     | |__________________________________________________- casting happend here
> 691 |   ...                   let candidates = unsafe { &(*goal_seq_ptr) };
>     |                                                   ^^^^^^^^^^^^^^^^
>     |
>     = note: casting from `rcl::humble::bindgen_action_msgs__msg__GoalInfo__Sequence` (16 bytes) to `goal_info::GoalInfoSeq<0>` (24 bytes)
> 
> error: could not compile `safe_drive` (lib) due to 2 previous errors
> ```

**Comment by ytakano** [comment]
https://doc.rust-lang.org/std/os/raw/type.c_ulong.html
> Most notably, many Linux-based systems assume an u64, but Windows assumes u32.

**Comment by jazi007** [comment]
Nice catch, let me know when a new commit is added to fix this I will give it a try

**Comment by ytakano** [comment]
@jazi007 
I think I could fix.

Please reinstall https://github.com/tier4/cargo-ament-build and use 0.3.13 of https://crates.io/crates/safe_drive .

**Comment by jazi007** [comment]
@ytakano perfect, fix is working thanks, closing this PR ;)

**Pull request closed without merging**
